##---------------------------------------------------------------------------##
# Service Configuration
##---------------------------------------------------------------------------##
debug: ${DEBUG_MODE:false}

server:
  port: ${SERVER_PORT:8080}

serviceId: ${SERVICE_ID:batch-decisions}

##---------------------------------------------------------------------------##
spring:
  application:
    name: batch-decisions

##---------------------------------------------------------------------------##
# BATCH CONFIGURATION

  ## H2 Servlet setting (disabled for now)
  ## connection URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /admin/h2


##---------------------------------------------------------------------------##
# MODULE SPECIFIC PROPERTIES

spring.batch.job.enabled: ${BATCH_JOB_ENABLED:false}


##---------------------------------------------------------------------------##
# Logging and Console

logging:
  level:
    io.baselogic: 'DEBUG'

spring.main.banner-mode: ${BANNER_MODE:off}
#spring.main.banner-mode: ${BANNER_MODE:console}
spring.output.ansi.enabled: ${SPRING_ANSI_ENABLED:ALWAYS}


##---------------------------------------------------------------------------##
## NOTE: Enable Management endpoints

management:
  #  see ActuatorSecurity.java
  #  security:
  #    enabled: false

  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

  # Allow all details for Hystrix dashboard
  endpoint:
    health:
      show-details: always

##---------------------------------------------------------------------------##
#spring.profiles.active: SBA

##---------------------------------------------------------------------------##
## NOTE: Spring Boot Admin Application Profile Properties
---

spring:
  profiles: SBA


# SBA Client details:
spring.boot.admin.username: ${ADMIN_SERVER_USERNAME:admin}
spring.boot.admin.password: ${ADMIN_SERVER_PASSWORD:admin}

spring.boot.admin.client.url: ${ADMIN_SERVER_URL:http://localhost:1111}


##---------------------------------------------------------------------------##
